### ISSUE TITLE
Only intermittently working

### ISSUE THREAD

**Issue by davidrhoderick** [pocesar/angular-equalizer#9]
I am using this on a website I am developing with Grunt (in case my 'watch' task is interfering, though I doubt it) and it is only working very occasionally.  Here is my html

     <div ng-repeat="step in planActDone track by $index" class="step-container" id="step-{{$index}}">
      <div class="row vcol">
        <div class="col-sm-8 vtop">
          <div class="row">
            <div class="col-sm-6 text-center" equalizer="'group'" height="0">
              <h2 class="color-blue text-center step-title">{{step.title}}</h2>
              <img ng-src="{{step.screenshot}}" class="img-responsive screenshot">
            </div>
            <div class="col-sm-6 text-center" equalizer="'group'" height="0">
              <h2 class="color-blue step-header">{{step.header}}</h2>
              <div class="step-text-container">
                <p ng-bind-html="step.text" class="step-text"></p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

It is included in my app.js as a module along others.  Need more code or info?  Let me know.

**Comment by pocesar** [comment]
it seems that the height being forcefully set to 0, and an image loading at the same time can have unpredictable results indeed. if the image have no dimensions (like min-height on css), it will be hard for the directive to determine a common height. 
but you should notice that the container (in your example using bootstrap) is a float, which can further make it harder to either set or watch for.
try putting the directive with a div inside the col-sm-6 containers instead of on it

**Comment by pocesar** [comment]
new version 4.0.0 will update regardless of window resize events (tentatively at 60fps at most)
